version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    container_name: allegro-postgres-dev
    environment:
      POSTGRES_USER: sami
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cip
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - allegro-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sami -d cip"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  allegro-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
